package com.cryptomarket.cryptoexchange.interfeces;

import com.cryptomarket.cryptoexchange.utill.parserJsonCoinMarketCap.briefInformation.BriefDataAboutCrypto;
import com.cryptomarket.cryptoexchange.utill.parserJsonCoinMarketCap.finalView.CurrentInfoAboutCryptocurrency;

import java.util.ArrayList;
public interface ConvertInterface {
    ArrayList<CurrentInfoAboutCryptocurrency> getConvertDefaultInfoOfAllCryptocurrencyToCurrentInfoAboutCryptocurrency(ArrayList<BriefDataAboutCrypto> briefDataAboutCryptoArrayList);
}
